In [1]:
import numpy as np

# Create a new array

In [2]:
arr = np.arange(15)
arr
# arr = np.array(my_existing_list)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Reshape 2D matrice

In [3]:
two_d_arr = arr.reshape(3,5)
two_d_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Transpose the matrice

In [4]:
transposed_two_d_arr = two_d_arr.T
transposed_two_d_arr

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Rows and columns indexing

In [5]:
first_row = transposed_two_d_arr[0,0:] 
second_row = transposed_two_d_arr[1,0:]

In [6]:
print('First row: ',first_row,'\nSecond row: ',second_row)

First row:  [ 0  5 10] 
Second row:  [ 1  6 11]


In [7]:
first_col = transposed_two_d_arr[0:,0]
second_col = transposed_two_d_arr[0:,1]

In [8]:
print('First column: \n',first_col,'\nSecond column: \n',second_col)

First column: 
 [0 1 2 3 4] 
Second column: 
 [5 6 7 8 9]


# Basic operations and stat

In [9]:
np.multiply(first_col, second_col)

array([ 0,  6, 14, 24, 36])

In [10]:
new_arr = np.random.randn(5,5)
new_arr

array([[-0.95533736,  1.314161  , -1.52262406, -0.55347606, -0.19459267],
       [ 1.86621693, -0.65835607,  0.77122549, -1.31174363,  1.02353813],
       [-0.53660257,  0.1420919 ,  0.34816195, -0.18790636,  0.28425584],
       [-0.50314539, -0.15291942,  0.64367661,  0.32289517, -0.87012797],
       [ 0.38006325, -0.80740504,  0.82766886, -0.09455733, -0.32369967]])

In [11]:
mean_value = new_arr.mean()
mean_value

-0.029941538579121085

In [12]:
standard_dev = new_arr.std()
standard_dev

0.80627446570712424

In [13]:
x = np.where(new_arr < mean_value, 0, 1)
# where new_arr value is < than mean_value, value = 0, otherwise, value = 1
x

array([[0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 1, 0, 0]])

In [14]:
w_list = [0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,0,0,0,1,0,1,1,1,0]
w = np.array(w_list).reshape(5,5)
w

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0]])

In [15]:
y = np.multiply(x, w)
y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [16]:
print('Is y = x?\n',x == y)

Is y = x?
 [[ True False  True  True  True]
 [False  True False  True False]
 [ True False  True  True  True]
 [ True  True False False  True]
 [False  True  True  True  True]]


In [17]:
a = transposed_two_d_arr[0:,0]
b = transposed_two_d_arr[0:,1]
c = transposed_two_d_arr[0:,2]

In [18]:
print('a: ',a,'\nb: ',b,'\nc: ',c)

a:  [0 1 2 3 4] 
b:  [5 6 7 8 9] 
c:  [10 11 12 13 14]


In [19]:
a_and_c = np.concatenate((a, c), axis = 0)
a_and_c

array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14])